#!/bin/bash
#set -x
set -o nounset

cd $(dirname "$0")
config_dir=$(realpath .)

check_commands() {
	local missing=0
	for tool in "$@"; do
		if ! command -v "$tool" > /dev/null; then
			echo "$tool missing."
			missing=1
		fi
	done
	return $missing
}

config_backup_dir="backup-$(date +%F-%H-%M-%S)";

install_file() {
	if [ -e "$HOME/$2" ]; then
		if [ "$(readlink "$HOME/$2")" != "$config_dir/$1" ]; then
			mkdir -p "$config_backup_dir"
			mv "$HOME/$2" "$config_backup_dir/$1"
			echo "'$2' already exists. It is moved to '$config_dir/$config_backup_dir/$1'." 1>&2
		fi
	fi
	# FIXME: This creates a symlink in symlink for folders, not sure how to suppress this.
	ln -fs "$config_dir/$1" "$HOME/$2"
}

# Install configuration files.
for file in aliases bash_profile bashrc gitconfig profile shellrc tmux.conf
do
	install_file "$file" ".$file"
done

mkdir -p "$HOME/.config"
install_file "fish" ".config/fish"
install_file "helix" ".config/helix"
install_file "kitty" ".config/kitty"
install_file "git" ".config/git"
install_file "starship.toml" ".config/starship.toml"

mkdir -p "$HOME/.ssh"
install_file "ssh-config" ".ssh/config"
install_file "ssh-allowed_signers" ".ssh/allowed_signers"
