theme = "bogster"

[editor]
line-number = "relative"
mouse = false
cursorline=true
idle-timeout=10
scrolloff=20
auto-pairs = true
# Can be annoying when files are being watched.
auto-save = false
color-modes = true
bufferline = "always"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
right = ["diagnostics", "workspace-diagnostics", "selections", "position", "version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "bar"

[keys.insert]
right = "no_op"
left = "no_op"
up = "no_op"
down = "no_op"
C-space = "signature_help"

[keys.normal]
C-r = ":reflow"
backspace = ":w"
V = ["goto_first_nonwhitespace", "extend_to_line_end"]
x = ["extend_line"]

[keys.normal.space]
"H" = ":toggle lsp.display-inlay-hints"

[keys.select]
";" = ["collapse_selection", "normal_mode"]
V = ["extend_to_line_end"]
