theme = "bogster"

[editor]
# line-number = "relative"
mouse = false
cursorline=true
idle-timeout=10
scrolloff=20
auto-pairs = true
auto-save = true
color-modes = true
bufferline = "always"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[keys.insert]
right = "no_op"
left = "no_op"
up = "no_op"
down = "no_op"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.statusline]
right = ["diagnostics", "workspace-diagnostics", "selections", "position", "version-control"]

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "bar"

[keys.normal]
C-r = ":reflow"
backspace = ":w"

[keys.normal.space]
"H" = ":toggle lsp.display-inlay-hints"
