[language-server.rust-analyzer.config.check]
command = "clippy"

[[language]]
name = "html"
# this auto format does not take conflict markers into account, that is a little annoying, so sometimes it is good to disable.
auto-format = false
language-servers = ["harper-ls", "vscode-html-language-server"]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
spaces = false
sentence_capitalization = false
